services:
  postgres:
    image: postgres:16-alpine
    container_name: trustbridge_db
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - trustbridge_data:/var/lib/postgresql/data # Changed to a named volume

volumes:
  trustbridge_data: # Define the volume here